"use client";

// ---------------------------------------------------------------------------
// SecureCaseVault — AI Document Intelligence
//
// Displays structured security intelligence generated by the document
// analysis pipeline.
//
// IMPORTANT:
// Results are advisory and require human verification.
// ---------------------------------------------------------------------------

import { useState } from "react";
import { useRouter } from "next/navigation";

import { AI_STATUS_META, formatDateTime } from "@/lib/format";
import { Badge, Spinner } from "./ui";
import { IconActivity } from "./icons";

export interface AnalysisView {
  status: string;

  category: string | null;
  summary: string | null;
  keywords: string[] | null;

  riskLevel: string | null;
  threatType: string | null;
  confidence: number | null;

  keyFindings: string[] | null;
  timeline: string[] | null;
  recommendedActions: string[] | null;

  provider: string | null;
  error: string | null;
  processedAt: string | null;
}

function riskTone(risk: string | null) {
  switch (risk?.toUpperCase()) {
    case "CRITICAL":
      return "red";
    case "HIGH":
      return "amber";
    case "MEDIUM":
      return "violet";
    case "LOW":
      return "green";
    default:
      return "slate";
  }
}

function riskLabel(risk: string | null) {
  return risk?.toUpperCase() || "UNKNOWN";
}

export default function AiAnalysisCard({
  documentId,
  analysis,
}: {
  documentId: number;
  analysis: AnalysisView | null;
}) {
  const router = useRouter();

  const [loading, setLoading] = useState(false);

  async function analyze() {
    setLoading(true);

    try {
      await fetch(`/api/documents/${documentId}/analyze`, {
        method: "POST",
      });

      router.refresh();
    } finally {
      setLoading(false);
    }
  }

  const statusMeta = analysis
    ? (AI_STATUS_META[analysis.status] ?? {
        label: analysis.status,
        tone: "slate" as const,
      })
    : null;

  const busy =
    loading ||
    analysis?.status === "processing" ||
    analysis?.status === "pending";

  return (
    <div className="card p-5 anim-rise-1">
      {/* ------------------------------------------------------------------ */}
      {/* Header                                                             */}
      {/* ------------------------------------------------------------------ */}

      <div className="flex flex-wrap items-center gap-3">
        <span className="flex h-9 w-9 items-center justify-center rounded-lg border border-violet-400/30 bg-violet-400/10 text-violet-300">
          <IconActivity className="h-[18px] w-[18px]" />
        </span>

        <div className="mr-auto">
          <h2 className="font-display text-sm font-semibold">
            AI Document Intelligence
          </h2>

          <p className="text-[11px] text-mut-2">
            Security analysis — results require human verification
          </p>
        </div>

        {statusMeta && (
          <Badge
            tone={statusMeta.tone}
            dot={analysis?.status === "processing"}
          >
            {statusMeta.label}
          </Badge>
        )}

        <button
          className="btn btn-primary"
          onClick={analyze}
          disabled={busy}
        >
          {busy ? <Spinner /> : null}
          {busy
            ? "Analyzing…"
            : analysis
              ? "Re-analyze with AI"
              : "Analyze with AI"}
        </button>
      </div>

      {/* ------------------------------------------------------------------ */}
      {/* Completed Analysis                                                */}
      {/* ------------------------------------------------------------------ */}

      {analysis?.status === "completed" && (
        <div className="mt-5 space-y-5">
          {/* -------------------------------------------------------------- */}
          {/* Risk Overview                                                  */}
          {/* -------------------------------------------------------------- */}

          <div className="grid gap-3 md:grid-cols-3">
            <div className="rounded-xl border border-line-2 bg-field p-4">
              <p className="text-[10px] font-bold uppercase tracking-wider text-mut-2">
                Risk Level
              </p>

              <div className="mt-2">
                <Badge tone={riskTone(analysis.riskLevel) as any}>
                  {riskLabel(analysis.riskLevel)}
                </Badge>
              </div>
            </div>

            <div className="rounded-xl border border-line-2 bg-field p-4">
              <p className="text-[10px] font-bold uppercase tracking-wider text-mut-2">
                Threat Type
              </p>

              <p className="mt-2 text-sm font-semibold text-mut">
                {analysis.threatType || "No threat type detected"}
              </p>
            </div>

            <div className="rounded-xl border border-line-2 bg-field p-4">
              <p className="text-[10px] font-bold uppercase tracking-wider text-mut-2">
                Confidence
              </p>

              <div className="mt-2 flex items-center gap-3">
                <div className="h-2 flex-1 overflow-hidden rounded-full bg-line-2">
                  <div
                    className="h-full rounded-full bg-violet-400"
                    style={{
                      width: `${Math.min(
                        Math.max(analysis.confidence ?? 0, 0),
                        100,
                      )}%`,
                    }}
                  />
                </div>

                <span className="text-sm font-bold text-violet-200">
                  {analysis.confidence ?? 0}%
                </span>
              </div>

              <p className="mt-1 text-[10px] text-mut-2">
                Prototype confidence score
              </p>
            </div>
          </div>

          {/* -------------------------------------------------------------- */}
          {/* Classification                                                 */}
          {/* -------------------------------------------------------------- */}

          <div className="flex flex-wrap items-center gap-2">
            <span className="text-[11px] font-bold uppercase tracking-wider text-mut-2">
              Document Classification
            </span>

            <Badge tone="violet">
              {analysis.category ?? "Other"}
            </Badge>

            {analysis.provider && (
              <span className="ml-auto text-[11px] font-semibold text-mut-2">
                {analysis.provider}
              </span>
            )}
          </div>

          {/* -------------------------------------------------------------- */}
          {/* Threat Intelligence                                            */}
          {/* -------------------------------------------------------------- */}

          {analysis.keyFindings &&
            analysis.keyFindings.length > 0 && (
              <div>
                <p className="mb-2 text-[11px] font-bold uppercase tracking-wider text-mut-2">
                  Key Findings
                </p>

                <div className="space-y-2">
                  {analysis.keyFindings.map((finding, index) => (
                    <div
                      key={`${finding}-${index}`}
                      className="flex gap-3 rounded-lg border border-line-2 bg-field px-3 py-2.5"
                    >
                      <span className="mt-0.5 text-amber-300">
                        ⚠
                      </span>

                      <p className="text-sm leading-relaxed text-mut">
                        {finding}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}

          {/* -------------------------------------------------------------- */}
          {/* Timeline                                                        */}
          {/* -------------------------------------------------------------- */}

          {analysis.timeline &&
            analysis.timeline.length > 0 && (
              <div>
                <p className="mb-2 text-[11px] font-bold uppercase tracking-wider text-mut-2">
                  Incident Timeline
                </p>

                <div className="overflow-hidden rounded-xl border border-line-2">
                  {analysis.timeline.map((event, index) => {
                    const separatorIndex = event.indexOf(" — ");

                    const time =
                      separatorIndex > -1
                        ? event.slice(0, separatorIndex)
                        : "";

                    const description =
                      separatorIndex > -1
                        ? event.slice(separatorIndex + 3)
                        : event;

                    return (
                      <div
                        key={`${event}-${index}`}
                        className="flex gap-4 border-b border-line-2 bg-field px-4 py-3 last:border-b-0"
                      >
                        <span className="min-w-[52px] font-mono text-xs font-bold text-cyan-300">
                          {time}
                        </span>

                        <span className="text-sm leading-relaxed text-mut">
                          {description}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

          {/* -------------------------------------------------------------- */}
          {/* Recommended Actions                                            */}
          {/* -------------------------------------------------------------- */}

          {analysis.recommendedActions &&
            analysis.recommendedActions.length > 0 && (
              <div>
                <p className="mb-2 text-[11px] font-bold uppercase tracking-wider text-mut-2">
                  Recommended Actions
                </p>

                <div className="space-y-2">
                  {analysis.recommendedActions.map(
                    (action, index) => (
                      <div
                        key={`${action}-${index}`}
                        className="flex gap-3 rounded-lg border border-line-2 bg-field px-3 py-2.5"
                      >
                        <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-violet-400/30 bg-violet-400/10 text-[10px] font-bold text-violet-300">
                          {index + 1}
                        </span>

                        <p className="text-sm leading-relaxed text-mut">
                          {action}
                        </p>
                      </div>
                    ),
                  )}
                </div>
              </div>
            )}

          {/* -------------------------------------------------------------- */}
          {/* AI Summary                                                     */}
          {/* -------------------------------------------------------------- */}

          <div>
            <p className="mb-1 text-[11px] font-bold uppercase tracking-wider text-mut-2">
              AI Summary

              {analysis.provider &&
                !analysis.provider.startsWith("External") && (
                  <span className="ml-2 rounded border border-amber-400/30 bg-amber-400/10 px-1.5 py-0.5 text-[10px] font-bold text-amber-300">
                    PROTOTYPE ANALYSIS
                  </span>
                )}
            </p>

            <p className="whitespace-pre-wrap text-sm leading-relaxed text-mut">
              {analysis.summary}
            </p>
          </div>

          {/* -------------------------------------------------------------- */}
          {/* Keywords                                                       */}
          {/* -------------------------------------------------------------- */}

          {analysis.keywords &&
            analysis.keywords.length > 0 && (
              <div>
                <p className="mb-1.5 text-[11px] font-bold uppercase tracking-wider text-mut-2">
                  Keywords
                </p>

                <div className="flex flex-wrap gap-1.5">
                  {analysis.keywords.map((keyword, index) => (
                    <span
                      key={`${keyword}-${index}`}
                      className="rounded-md border border-line-2 bg-field px-2 py-1 font-mono text-[11px] text-cyan-200/90"
                    >
                      {keyword}
                    </span>
                  ))}
                </div>
              </div>
            )}

          {/* -------------------------------------------------------------- */}
          {/* Analysis Time                                                  */}
          {/* -------------------------------------------------------------- */}

          {analysis.processedAt && (
            <p className="text-[11px] text-mut-2">
              Analyzed {formatDateTime(analysis.processedAt)}
            </p>
          )}

          {/* -------------------------------------------------------------- */}
          {/* Human Verification Warning                                     */}
          {/* -------------------------------------------------------------- */}

          <div className="rounded-lg border border-amber-400/25 bg-amber-400/5 px-3 py-2.5 text-[11px] leading-relaxed text-amber-200/90">
            <strong>Human verification required.</strong>{" "}
            AI-generated results are advisory and may contain errors.
            This prototype does not establish legal conclusions or
            replace investigator review.
          </div>
        </div>
      )}

      {/* ------------------------------------------------------------------ */}
      {/* Failed                                                             */}
      {/* ------------------------------------------------------------------ */}

      {analysis?.status === "failed" && (
        <div className="mt-4">
          <p className="text-sm font-semibold text-mut">
            AI analysis unavailable for this document.
          </p>

          {analysis.error && (
            <p className="mt-1 text-xs leading-relaxed text-mut-2">
              {analysis.error}
            </p>
          )}

          <p className="mt-2 text-[11px] text-mut-2">
            You can retry — the document itself is unaffected by
            analysis failures.
          </p>
        </div>
      )}

      {/* ------------------------------------------------------------------ */}
      {/* Not Yet Analyzed                                                  */}
      {/* ------------------------------------------------------------------ */}

      {!analysis && (
        <p className="mt-4 text-sm leading-relaxed text-mut-2">
          No analysis yet. Run the document intelligence pipeline to
          extract text, classify the document, identify security
          indicators, generate a timeline and recommend investigation
          actions. Decryption happens temporarily in memory during
          analysis.
        </p>
      )}
    </div>
  );
}